// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class 修改了attributes的类型 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改了attributes的类型));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200653273_修改了attributes的类型"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
